In [1]:
import numpy as np 
import pandas as pd 
import json
import os 
import matplotlib.pyplot as plt

In [2]:
PARSED_FILE = './parsed.json'
with open(PARSED_FILE, 'r') as json_file:
    data = json.load(json_file)

# Create a DataFrame from the list of dictionaries
df = pd.json_normalize(data)
df

,workload,discards,foundbug,strategy,mutant,passed,property,time
0,RBT,0,False,bespokeGenerator,miscolor_balRight,1000,prop_DeleteDelete,97.98
1,RBT,0,False,bespokeGenerator,miscolor_balRight,1000,prop_DeleteDelete,84.39
2,RBT,0,False,bespokeGenerator,miscolor_balRight,1000,prop_DeleteDelete,86.22
3,RBT,0,False,bespokeGenerator,miscolor_balRight,1000,prop_DeleteDelete,87.34
4,RBT,0,False,bespokeGenerator,miscolor_balRight,1000,prop_DeleteDelete,72.67
...,...,...,...,...,...,...,...,...
2215,BST,0,True,bespokeGenerator,union_7,0,prop_UnionModel,0.15
2216,BST,0,True,bespokeGenerator,union_7,0,prop_UnionModel,0.14
2217,BST,0,True,bespokeGenerator,union_7,0,prop_UnionModel,0.33
2218,BST,0,True,bespokeGenerator,union_7,0,prop_UnionModel,3.70
2219,BST,0,True,bespokeGenerator,union_7,1,prop_UnionModel,0.22

In [5]:
rbt = df[df['workload'] == 'RBT']
print("RBT, Type-Based Generator:")
display(rbt[rbt['strategy'] == 'typeBasedGenerator'].describe())
print("RBT, Bespoke Generator:")
display(rbt[rbt['strategy'] == 'bespokeGenerator'].describe())

RBT, Type-Based Generator:

          discards      passed        time
count   580.000000  580.000000  580.000000
mean    735.596552   91.787931  218.429690
std     448.662260   57.204371  138.128859
min       0.000000    0.000000    0.090000
25%     209.000000   26.000000   64.297500
50%    1057.000000  124.000000  278.600000
75%    1069.000000  135.250000  324.757500
max    1097.000000  165.000000  448.610000

RBT, Bespoke Generator:

       discards       passed        time
count     580.0   580.000000  580.000000
mean        0.0   242.713793   21.720759
std         0.0   371.450182   33.133926
min         0.0     0.000000    0.100000
25%         0.0     3.000000    0.330000
50%         0.0    33.500000    3.295000
75%         0.0   294.000000   27.707500
max         0.0  1000.000000  108.520000